"""New revision

Revision ID: 7ac30015c54a
Revises: 
Create Date: 2025-01-30 17:11:03.793844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ac30015c54a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prepared_sandboxes', sa.Column('modal_sandbox_id', sa.String(), nullable=True))
    op.add_column('prepared_sandboxes', sa.Column('modal_volume_label', sa.String(), nullable=True))
    op.drop_column('prepared_sandboxes', 'docker_container_id')
    op.drop_column('prepared_sandboxes', 'docker_volume_label')
    op.add_column('projects', sa.Column('modal_sandbox_last_used_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('modal_sandbox_id', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('modal_sandbox_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('modal_volume_label', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('stack_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'projects', 'stacks', ['stack_id'], ['id'])
    op.drop_column('projects', 'docker_fe_container_id')
    op.drop_column('projects', 'fe_port')
    op.drop_column('projects', 'be_port')
    op.drop_column('projects', 'docker_be_container_id')
    op.add_column('stacks', sa.Column('preview_url', sa.String(), nullable=True))
    op.add_column('stacks', sa.Column('stack_type', sa.Enum('FRONTEND', 'BACKEND', 'OTHER', name='stacktype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stacks', 'stack_type')
    op.drop_column('stacks', 'preview_url')
    op.add_column('projects', sa.Column('docker_be_container_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('be_port', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('fe_port', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('docker_fe_container_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'stack_id')
    op.drop_column('projects', 'modal_volume_label')
    op.drop_column('projects', 'modal_sandbox_expires_at')
    op.drop_column('projects', 'modal_sandbox_id')
    op.drop_column('projects', 'modal_sandbox_last_used_at')
    op.add_column('prepared_sandboxes', sa.Column('docker_volume_label', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('prepared_sandboxes', sa.Column('docker_container_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('prepared_sandboxes', 'modal_volume_label')
    op.drop_column('prepared_sandboxes', 'modal_sandbox_id')
    # ### end Alembic commands ###
